"""``Cost(C, I, theta)``: the expected cost of one run of the protocol.

Committing the boundary ``∂ = In ∪ ⋃_r Out(R_r)`` costs ``h`` per position; a
replay unit, selected with probability ``q``, costs ``h`` per interior
position it commits (its gates but ``Out`` and its pinned source gates) and
the recomputation of its interior; a verification unit, selected with
probability ``q s``, costs its proof and a fixed ``c_0``::

    Cost = h |∂| + Recompute + q sum_r h |Int(r)| + q s sum_v (Cost_proof(V_v) + c_0)

**The retention assumption.**  The honest prover retains only the circuit
inputs and the weights; every other value is regenerated by re-executing the
smallest closed unit that contains the sampled unit.  A kind is *closed*
(:attr:`~veritor.core.KindSummary.closed`) when every port of it, at every
call site, is fed a source gate: a closed replay unit can be replayed from
what the prover has, so it costs its own ``Cost_replay`` with probability
``q``.  Any other replay unit reads values the prover no longer holds (an
activation, a cache entry, an earlier token), and regenerating them means
re-executing its *recomputation unit*: the smallest closed kind on the path
from the unit up to the root (the root has no ports and is always closed, so
it exists).  Sampling any of the ``m_A`` replay units whose recomputation
unit is ``A`` forces one re-execution of ``A``, so with independent sampling
at rate ``q``::

    Recompute = sum over closed kinds A of  copies_A * (1 - (1 - q)^{m_A}) * Cost_replay(A)

corrected for nesting: when closed kinds nest (a request holds a prefill,
both closed), a re-execution of the outer one already regenerates the
inner, so the inner is charged only when the outer is not re-executed
(``(1 - p_outer)`` times its own term).  This is the exact expectation
under independent sampling, never above the plain sum.  For a closed replay
unit ``m = 1`` and the term is ``q Cost_replay``, the cost of honest replay;
for fine replay units inside a request ``m`` is in the millions and the term
is the whole request with probability ``1 - (1 - q)^m ≈ 1``.

``(1 - q)^m`` is exact while ``m * bit_length(denominator(1 - q))`` stays
within :data:`EXACT_BITS`; past that it is ``0`` when ``q m > 64`` (the
probability is ``1`` to within ``2^-64``) and otherwise a float
``exp(m log1p(-q))`` turned back into a ``Fraction`` (see :func:`survival`).

The weights are committed once per epoch under κ_W, ``h |W|``, reported
separately from the per-run total.  Everything is a count per kind weighted
by copies, so the fold is ``O(#kinds)``.  The verifier's own expected work is
priced by :func:`veritor.protocol.expected_work`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from fractions import Fraction

from veritor.core.compiled import Compiled, as_kind_table
from veritor.core.description import REPLAY, VERIFICATION
from veritor.core.index import KindSummary, KindTable
from veritor.core.policy import ProbabilityInput, VerificationPolicy, exact_fraction

EXACT_BITS = 4096
"""``(1 - q)^m`` is computed exactly while ``m * bit_length(denominator(1 - q))`` is at most this."""

CERTAIN_MASS = 64
"""``1 - (1 - q)^m`` is taken as ``1`` when ``q m`` exceeds this (the error is below ``2^-64``)."""


@dataclass(frozen=True, slots=True, init=False)
class CostParameters:
    """``h``, the cost of committing one position, and ``c_0``, the fixed cost of one proof."""

    hash_cost: Fraction
    proof_overhead: Fraction

    def __init__(self, hash_cost: ProbabilityInput = 1, proof_overhead: ProbabilityInput = 0) -> None:
        for name, value in (("hash_cost", hash_cost), ("proof_overhead", proof_overhead)):
            checked = exact_fraction(value, name=name)
            if checked < 0:
                raise ValueError(f"{name} must be nonnegative")
            object.__setattr__(self, name, checked)


@dataclass(frozen=True, slots=True)
class ExpectedCost:
    """The per-run terms of the expected cost, exactly, and the per-epoch weight commitment.

    ``recompute`` is the re-execution of the recomputation units of the
    sampled replay units, ``commit_interior`` the ``h`` per interior
    position the sampled replay units commit; ``replay`` is their sum, the
    cost of the replay phase.  ``weights`` is ``h |W|``: paid once per epoch
    when κ_W is built, not per run, so it is not part of ``total``.
    """

    boundary: Fraction
    recompute: Fraction
    commit_interior: Fraction
    proof: Fraction
    weights: Fraction = Fraction(0)

    @property
    def replay(self) -> Fraction:
        return self.recompute + self.commit_interior

    @property
    def total(self) -> Fraction:
        return self.boundary + self.recompute + self.commit_interior + self.proof


def survival(q: Fraction, m: int) -> Fraction:
    """``(1 - q)^m``: the probability that none of ``m`` units sampled independently at rate ``q`` is drawn.

    Exact while the result stays small (``m * bit_length(denominator) <=``
    :data:`EXACT_BITS`); ``0`` when ``q m >`` :data:`CERTAIN_MASS`; otherwise
    the float ``exp(m log1p(-q))`` as an exact binary fraction.
    """

    if m < 0:
        raise ValueError("m must be nonnegative")
    miss = 1 - q
    if m * miss.denominator.bit_length() <= EXACT_BITS:
        return miss**m
    if q * m > CERTAIN_MASS:
        return Fraction(0)
    return Fraction.from_float(math.exp(m * math.log1p(-float(q))))


def recomputation_units(table: KindTable) -> dict[str, int]:
    """``m_A`` per closed kind ``A``: the replay units whose recomputation unit is ``A``.

    A closed replay unit is its own recomputation unit (``m = 1``); a replay
    unit that is not closed counts towards the nearest closed kind above it.
    Kinds with ``m = 0`` (nothing replayable is charged to them) are omitted.
    """

    rows = {row.kind: row for row in table.rows}
    pending: dict[str, int] = {}
    found: dict[str, int] = {}

    def fold(kind: str) -> int:
        """Replay units at or under one copy of ``kind`` not yet charged to a closed kind."""

        cached = pending.get(kind)
        if cached is not None:
            return cached
        row = rows[kind]
        if row.role == REPLAY:
            count = 0 if row.closed else 1
            if row.closed:
                found[kind] = 1
        else:
            count = sum(copies * fold(child) for child, copies in row.children)
            if row.closed and count:
                found[kind] = count
            if row.closed:
                count = 0
        pending[kind] = count
        return count

    fold(table.root)
    return found


def cost(
    target: Compiled | KindTable,
    policy: VerificationPolicy,
    parameters: CostParameters | None = None,
) -> ExpectedCost:
    """Fold the expected cost of ``policy`` over the kinds of ``target`` (an artifact or its table)."""

    table = as_kind_table(target)
    if not isinstance(policy, VerificationPolicy):
        raise TypeError("policy must be a VerificationPolicy")
    parameters = CostParameters() if parameters is None else parameters
    h, c0 = parameters.hash_cost, parameters.proof_overhead
    boundary = Fraction(table.input_count)  # the input gates, then every unit's Out
    interior_total = Fraction(0)
    proof = Fraction(0)
    for kind in table.rows:
        if kind.role == REPLAY:
            boundary += kind.copies * kind.out_count
            interior = kind.size - kind.out_count - kind.source_inputs - kind.source_weights
            interior_total += kind.copies * h * interior
        elif kind.role == VERIFICATION:
            proof += kind.copies * (kind.proof_cost + c0)
    return ExpectedCost(
        h * boundary,
        _recompute(table, policy.q),
        policy.q * interior_total,
        policy.q * policy.s * proof,
        h * table.weight_count,
    )


def _recompute(table: KindTable, q: Fraction) -> Fraction:
    """The expected re-execution cost of one run: the nested sum of the module docstring."""

    rows = {row.kind: row for row in table.rows}
    units = recomputation_units(table)
    expected: dict[str, Fraction] = {}

    def fold(row: KindSummary) -> Fraction:
        """Expected recomputation charged inside one copy of ``row``, no closed ancestor re-executed."""

        cached = expected.get(row.kind)
        if cached is not None:
            return cached
        inner = Fraction(0)
        if row.role != REPLAY:  # nothing below a replay unit is a replay unit
            inner = sum((copies * fold(rows[child]) for child, copies in row.children), Fraction(0))
        m = units.get(row.kind, 0)
        if m:
            hit = 1 - survival(q, m)
            result = hit * row.replay_cost + (1 - hit) * inner
        else:
            result = inner
        expected[row.kind] = result
        return result

    return fold(rows[table.root])


__all__ = ["CERTAIN_MASS", "EXACT_BITS", "CostParameters", "ExpectedCost", "cost", "recomputation_units", "survival"]
