"""``python -m veritor.stress.report``: render the results tables of the stress documents.

Two tables.  The catalogue's (``docs/stress-tests.md``, ``## 4. Results``)
merges every ``docs/data/stress*.json`` except the honest-prover file by
scenario ID (later files win on a tie); the honest-prover programme's
(``docs/honest-prover.md``, ``## Results``) renders ``stress-honest.json``
alone, with the columns that programme measures.  Everything above a results
heading is left untouched.  ``--check`` exits non-zero instead of writing when
a document is stale.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from veritor.stress.rows import Row, load, row_key

__all__ = [
    "COLUMNS",
    "HEADING",
    "HONEST",
    "STRESS",
    "TABLES",
    "Table",
    "load_all",
    "main",
    "render",
    "update",
]

HEADING = "## 4. Results"
COLUMNS = (
    "ID",
    "What happened",
    "Mechanism",
    "Advice bits",
    "U (λ = 40)",
    "Overhead",
    "Description bytes",
    "Verdict",
)
HONEST_COLUMNS = (
    "ID",
    "What happened",
    "Mechanism",
    "Declarations",
    "Charge (bits)",
    "Recompute",
    "U (λ = 40)",
    "Verdict",
)
_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_DOCUMENT = _ROOT / "docs" / "stress-tests.md"
DEFAULT_HONEST_DOCUMENT = _ROOT / "docs" / "honest-prover.md"
DEFAULT_DATA = _ROOT / "docs" / "data"
HONEST_FILE = "stress-honest.json"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _overhead(value: float) -> str:
    return f"{value:.3g}" if value < 100 else f"{value:,.0f}"


def _extra_int(row: Row, name: str) -> str:
    value = row.extra.get(name)
    return (
        f"{value:,}" if isinstance(value, int) and not isinstance(value, bool) else "—"
    )


def _extra_fraction(row: Row, name: str) -> str:
    value = row.extra.get(name)
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return "—"
    return f"{float(value):.3g}"


def _stress_cells(row: Row) -> tuple[str, ...]:
    return (
        row.id,
        _cell(row.what),
        _cell(row.mechanism),
        f"{row.advice_bits:,}",
        f"{row.capacity_bits:,}",
        _overhead(row.overhead),
        f"{row.description_bytes:,}",
        _cell(row.verdict),
    )


def _honest_cells(row: Row) -> tuple[str, ...]:
    return (
        row.id,
        _cell(row.what),
        _cell(row.mechanism),
        _extra_int(row, "declarations"),
        _extra_int(row, "charge_bits"),
        _extra_fraction(row, "recompute"),
        f"{row.capacity_bits:,}",
        _cell(row.verdict),
    )


@dataclass(frozen=True, slots=True)
class Table:
    """One rendered results table: its document and heading, the data files that feed it, its columns."""

    document: Path
    heading: str
    pattern: str
    exclude: frozenset[str]
    columns: tuple[str, ...]
    cells: Callable[[Row], tuple[str, ...]]
    preamble: str

    def sources(self, directory: Path) -> list[Path]:
        return sorted(
            path
            for path in directory.glob(self.pattern)
            if path.name not in self.exclude
        )


STRESS = Table(
    document=DEFAULT_DOCUMENT,
    heading=HEADING,
    pattern="stress*.json",
    exclude=frozenset({HONEST_FILE}),
    columns=COLUMNS,
    cells=_stress_cells,
    preamble=(
        "`U` is `Bound` at `eta = 2^-40`, overhead is `Cost(...).total` over the honest "
        "replay cost at the simulation's policy `theta = (1/2, 1/8)`."
    ),
)
HONEST = Table(
    document=DEFAULT_HONEST_DOCUMENT,
    heading="## Results",
    pattern=HONEST_FILE,
    exclude=frozenset(),
    columns=HONEST_COLUMNS,
    cells=_honest_cells,
    preamble=(
        "declarations are what the honest prover had to declare for the run to be "
        "accepted, the charge is what those declarations add to `U` under the price "
        "the mechanism's stage admits (`docs/notes/late-advice.md`), recompute is the "
        "fraction of the production computation the prover re-executed to know what to "
        "declare, `U` is `Bound` at `eta = 2^-40` including the charge."
    ),
)
TABLES = (STRESS, HONEST)


def load_all(directory: Path, table: Table = STRESS) -> dict[str, Row]:
    """Rows of every data file of ``table`` in ``directory``, merged by ID."""

    rows: dict[str, Row] = {}
    for path in table.sources(directory):
        rows.update(load(path))
    return rows


def render(
    rows: Mapping[str, Row], sources: Sequence[Path] = (), table: Table = STRESS
) -> str:
    """The Markdown body of ``table``'s results section."""

    names = ", ".join(f"`docs/data/{path.name}`" for path in sources) or (
        f"`docs/data/{table.pattern}`"
    )
    preamble = (
        f"Generated by `python -m veritor.stress.report` from {names}; {table.preamble}"
    )
    lines = [
        preamble,
        "",
        "| " + " | ".join(table.columns) + " |",
        "|" + "---|" * len(table.columns),
    ]
    ordered = [rows[identifier] for identifier in sorted(rows, key=row_key)]
    lines.extend("| " + " | ".join(table.cells(row)) + " |" for row in ordered)
    noted = [row for row in ordered if row.notes]
    if noted:
        lines.extend(["", "Notes:", ""])
        lines.extend(f"- **{row.id}**: {_cell(row.notes)}" for row in noted)
    return "\n".join(lines) + "\n"


def update(document: str, body: str, heading: str = HEADING) -> str:
    """``document`` with everything after the results heading replaced by ``body``."""

    head, separator, _ = document.partition(f"\n{heading}\n")
    if not separator:
        raise ValueError(f"the document has no {heading!r} heading")
    return f"{head}{separator}\n{body}"


def _refresh(table: Table, document: Path, data: Path, check: bool) -> int:
    """Render ``table`` into ``document``; 0 when fresh or written, 1 when stale under ``check``."""

    sources = table.sources(data)
    if not sources:
        return 0
    rows = load_all(data, table)
    current = document.read_text(encoding="utf-8")
    rendered = update(current, render(rows, sources, table), table.heading)
    if rendered == current:
        return 0
    if check:
        print(
            f"{document} is stale; run python -m veritor.stress.report", file=sys.stderr
        )
        return 1
    document.write_text(rendered, encoding="utf-8")
    print(f"wrote {len(rows)} rows to {document}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--document", type=Path, default=DEFAULT_DOCUMENT)
    parser.add_argument("--honest-document", type=Path, default=DEFAULT_HONEST_DOCUMENT)
    parser.add_argument(
        "--data", type=Path, default=DEFAULT_DATA, help="directory of stress*.json"
    )
    parser.add_argument(
        "--check", action="store_true", help="fail instead of writing when stale"
    )
    arguments = parser.parse_args(argv)
    documents = {STRESS: arguments.document, HONEST: arguments.honest_document}
    return max(
        _refresh(table, documents[table], arguments.data, arguments.check)
        for table in TABLES
    )


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
