"""``python -m veritor.stress.report``: render the results section of ``docs/stress-tests.md``.

Every ``docs/data/stress*.json`` is merged by scenario ID (later files win on a
tie) and rendered as the table under ``## 4. Results``; everything above the
heading is left untouched.  ``--check`` exits non-zero instead of writing when
the document is stale.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path

from veritor.stress.rows import Row, load, row_key

__all__ = ["HEADING", "load_all", "main", "render", "update"]

HEADING = "## 4. Results"
COLUMNS = (
    "ID",
    "What happened",
    "Mechanism",
    "Advice bits",
    "U (λ = 40)",
    "Overhead",
    "Description bytes",
    "Verdict",
)
_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_DOCUMENT = _ROOT / "docs" / "stress-tests.md"
DEFAULT_DATA = _ROOT / "docs" / "data"


def load_all(directory: Path) -> dict[str, Row]:
    """Rows of every ``stress*.json`` in ``directory``, merged by ID."""

    rows: dict[str, Row] = {}
    for path in sorted(directory.glob("stress*.json")):
        rows.update(load(path))
    return rows


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _overhead(value: float) -> str:
    return f"{value:.3g}" if value < 100 else f"{value:,.0f}"


def render(rows: Mapping[str, Row], sources: Sequence[Path] = ()) -> str:
    """The Markdown body of the results section."""

    names = (
        ", ".join(f"`docs/data/{path.name}`" for path in sources)
        or "`docs/data/stress*.json`"
    )
    preamble = (
        f"Generated by `python -m veritor.stress.report` from {names}; "
        "`U` is `Bound` at `eta = 2^-40`, overhead is `Cost(...).total` over the honest "
        "replay cost at the simulation's policy `theta = (1/2, 1/8)`."
    )
    lines = [
        preamble,
        "",
        "| " + " | ".join(COLUMNS) + " |",
        "|" + "---|" * len(COLUMNS),
    ]
    ordered = [rows[identifier] for identifier in sorted(rows, key=row_key)]
    for row in ordered:
        cells = (
            row.id,
            _cell(row.what),
            _cell(row.mechanism),
            f"{row.advice_bits:,}",
            f"{row.capacity_bits:,}",
            _overhead(row.overhead),
            f"{row.description_bytes:,}",
            _cell(row.verdict),
        )
        lines.append("| " + " | ".join(cells) + " |")
    noted = [row for row in ordered if row.notes]
    if noted:
        lines.extend(["", "Notes:", ""])
        lines.extend(f"- **{row.id}**: {_cell(row.notes)}" for row in noted)
    return "\n".join(lines) + "\n"


def update(document: str, body: str) -> str:
    """``document`` with everything after the results heading replaced by ``body``."""

    head, separator, _ = document.partition(f"\n{HEADING}\n")
    if not separator:
        raise ValueError(f"the document has no {HEADING!r} heading")
    return f"{head}{separator}\n{body}"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--document", type=Path, default=DEFAULT_DOCUMENT)
    parser.add_argument(
        "--data", type=Path, default=DEFAULT_DATA, help="directory of stress*.json"
    )
    parser.add_argument(
        "--check", action="store_true", help="fail instead of writing when stale"
    )
    arguments = parser.parse_args(argv)
    sources = sorted(arguments.data.glob("stress*.json"))
    rows = load_all(arguments.data)
    current = arguments.document.read_text(encoding="utf-8")
    rendered = update(current, render(rows, sources))
    if rendered == current:
        return 0
    if arguments.check:
        print(
            f"{arguments.document} is stale; run python -m veritor.stress.report",
            file=sys.stderr,
        )
        return 1
    arguments.document.write_text(rendered, encoding="utf-8")
    print(f"wrote {len(rows)} rows to {arguments.document}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
