"""veritor: sampled verification of large circuits.

The paper-level API is ``Compile`` -> ``Verify`` / ``Bound`` -> ``Optimize``.
See ``veritor.research`` for the facade, ``veritor.protocol`` for the
two-stage protocol, and ``docs/`` for the paper.
"""

from veritor.research import (
    DEFAULT_CONFORMANCE_POLICY,
    AdditiveExpectedCost,
    AggregateBoundArtifact,
    ArchitectureCompileRequest,
    ArchitectureId,
    Bound,
    BoundOptionOverrides,
    BoundOptions,
    BoundOptionsInput,
    BoundResult,
    Compile,
    Compiled,
    CompileResult,
    DeepSeekV4ProCompileRequest,
    DemoGCompileRequest,
    ExecutableConformanceTranscript,
    Expectation,
    FiniteBoundSolver,
    FixedPolicyBoundResult,
    GPT2ClassGranularity,
    GPT2CompileRequest,
    GreedyTextExecutionShape,
    IndexedStructureArtifact,
    InklingCompileRequest,
    KimiK3CompileRequest,
    MatmulCompileRequest,
    OptimizationResult,
    Optimize,
    PolicyGridOptimizationResult,
    ProtocolRun,
    RationalPolicyGrid,
    TraceBinding,
    Unsupported,
    VerificationCode,
    VerificationLimits,
    VerificationPolicy,
    VerificationReport,
    Verify,
    build_executable_conformance_transcript,
    make_verification_expectation,
    run_protocol,
)

__all__ = [
    "DEFAULT_CONFORMANCE_POLICY",
    "AdditiveExpectedCost",
    "AggregateBoundArtifact",
    "ArchitectureCompileRequest",
    "ArchitectureId",
    "Bound",
    "BoundOptionOverrides",
    "BoundOptions",
    "BoundOptionsInput",
    "BoundResult",
    "Compile",
    "CompileResult",
    "Compiled",
    "DeepSeekV4ProCompileRequest",
    "DemoGCompileRequest",
    "ExecutableConformanceTranscript",
    "Expectation",
    "FiniteBoundSolver",
    "FixedPolicyBoundResult",
    "GPT2ClassGranularity",
    "GPT2CompileRequest",
    "GreedyTextExecutionShape",
    "IndexedStructureArtifact",
    "InklingCompileRequest",
    "KimiK3CompileRequest",
    "MatmulCompileRequest",
    "OptimizationResult",
    "Optimize",
    "PolicyGridOptimizationResult",
    "ProtocolRun",
    "RationalPolicyGrid",
    "TraceBinding",
    "Unsupported",
    "VerificationCode",
    "VerificationLimits",
    "VerificationPolicy",
    "VerificationReport",
    "Verify",
    "build_executable_conformance_transcript",
    "make_verification_expectation",
    "run_protocol",
]
