"""veritor: sampled verification of large circuits.

The paper-level API is ``Compile`` -> ``Verify`` / ``Bound`` / ``Cost`` -> ``Optimize``
(:mod:`veritor.research`).  Untrusted client-side code -- the tracer and the
built-in constructors -- lives in :mod:`veritor.constructors`; the two-stage
protocol in :mod:`veritor.protocol`; the paper in ``docs/``.
"""

from veritor.constructors import (
    DemoGCompileRequest,
    MatmulCompileRequest,
    Tracer,
    compile_demo_g,
    compile_matmul,
)
from veritor.core import make_word_gate_set
from veritor.research import (
    DEFAULT_CONFORMANCE_POLICY,
    Bound,
    BoundOptions,
    BoundResult,
    Capacity,
    Compilation,
    CompilationLimits,
    Compile,
    Compiled,
    Constructor,
    Cost,
    CostParameters,
    ExecutableConformanceTranscript,
    Expectation,
    ExpectedCost,
    GateSet,
    Optimization,
    Optimize,
    PolicyGrid,
    ProtocolRun,
    VerificationCode,
    VerificationLimits,
    VerificationPolicy,
    VerificationReport,
    VerifierParameters,
    Verify,
    Weights,
    build_executable_conformance_transcript,
    make_verification_expectation,
    run_protocol,
)

__all__ = [
    "DEFAULT_CONFORMANCE_POLICY",
    "Bound",
    "BoundOptions",
    "BoundResult",
    "Capacity",
    "Compilation",
    "CompilationLimits",
    "Compile",
    "Compiled",
    "Constructor",
    "Cost",
    "CostParameters",
    "DemoGCompileRequest",
    "ExecutableConformanceTranscript",
    "Expectation",
    "ExpectedCost",
    "GateSet",
    "MatmulCompileRequest",
    "Optimization",
    "Optimize",
    "PolicyGrid",
    "ProtocolRun",
    "Tracer",
    "VerificationCode",
    "VerificationLimits",
    "VerificationPolicy",
    "VerificationReport",
    "VerifierParameters",
    "Verify",
    "Weights",
    "build_executable_conformance_transcript",
    "compile_demo_g",
    "compile_matmul",
    "make_verification_expectation",
    "make_word_gate_set",
    "run_protocol",
]
