"""The objects of the paper: gate sets, circuits, the index, ``Compiled``, policies."""

from .circuit import (
    Circuit,
    CostKind,
    DescriptionCircuit,
    FlatCircuit,
    GateRef,
)
from .compiled import COMPILED_DIGEST_TAG, Compiled, as_kind_table
from .errors import CoreContractError, InvalidArtifact, ResourceLimit
from .gates import (
    GATE_SET_IDENTITY_TAG,
    INPUT_SOURCE,
    WEIGHT_SOURCE,
    Gate,
    GateSet,
    check_value,
    decode_value,
    encode_value,
    make_isa_gate_set,
    make_word_gate_set,
    value_byte_length,
)
from .identity import (
    Digest,
    JSONScalar,
    JSONValue,
    canonical_json,
    canonical_json_bytes,
    canonical_json_text,
    canonical_manifest_digest,
    identity_digest,
    tagged_sha256,
    validate_digest,
)
from .ids import Position, position
from .index import Index, IndexNode, KindSummary, KindTable, Units, validate_marks
from .indexed import (
    ExplicitDomain,
    ExplicitIndexedDomain,
    FiniteIndexedDomain,
    IndexedDomain,
    IntervalDifferenceDomain,
    IntervalDomain,
    LazyIndexedDomain,
    RangeDomain,
    RangeIndexedDomain,
    domains_equal,
    iter_domain,
    position_domain,
)
from .limits import CompilationLimits, VerificationLimits
from .ml_gates import make_ml_gate_set
from .policy import (
    ProbabilityInput,
    VerificationPolicy,
    exact_fraction,
    parse_probability,
    rational_manifest,
    rational_pair,
)

__all__ = [
    "COMPILED_DIGEST_TAG",
    "GATE_SET_IDENTITY_TAG",
    "INPUT_SOURCE",
    "WEIGHT_SOURCE",
    "Circuit",
    "CompilationLimits",
    "Compiled",
    "as_kind_table",
    "CoreContractError",
    "CostKind",
    "DescriptionCircuit",
    "Digest",
    "ExplicitDomain",
    "ExplicitIndexedDomain",
    "FiniteIndexedDomain",
    "FlatCircuit",
    "Gate",
    "GateRef",
    "GateSet",
    "Index",
    "IndexNode",
    "IndexedDomain",
    "IntervalDifferenceDomain",
    "IntervalDomain",
    "InvalidArtifact",
    "JSONScalar",
    "JSONValue",
    "KindSummary",
    "KindTable",
    "LazyIndexedDomain",
    "Position",
    "ProbabilityInput",
    "RangeDomain",
    "RangeIndexedDomain",
    "ResourceLimit",
    "Units",
    "VerificationLimits",
    "VerificationPolicy",
    "canonical_json",
    "canonical_json_bytes",
    "canonical_json_text",
    "canonical_manifest_digest",
    "check_value",
    "decode_value",
    "domains_equal",
    "encode_value",
    "exact_fraction",
    "identity_digest",
    "iter_domain",
    "make_isa_gate_set",
    "make_ml_gate_set",
    "make_word_gate_set",
    "parse_probability",
    "position",
    "position_domain",
    "rational_manifest",
    "rational_pair",
    "tagged_sha256",
    "validate_digest",
    "validate_marks",
    "value_byte_length",
]
from .silicon import (
    ADA_BF16_M16N8K16,
    ADA_E4M3_M16N8K32,
    AMPERE_BF16_M16N8K16,
    HAWKEYE_AMPERE_GROUPSUM_E4M3_V0,
    HOPPER_BF16_M16N8K16,
    HOPPER_E4M3_K32,
    PIPELINES,
    Pipeline,
    Term,
    group_sum,
    make_tensor_core_gate_set,
    tc_dot,
    tc_dot_chain,
)

__all__ += ["ADA_BF16_M16N8K16", "ADA_E4M3_M16N8K32", "AMPERE_BF16_M16N8K16", "HAWKEYE_AMPERE_GROUPSUM_E4M3_V0", "HOPPER_BF16_M16N8K16", "HOPPER_E4M3_K32", "PIPELINES", "Pipeline", "Term", "group_sum", "make_tensor_core_gate_set", "tc_dot", "tc_dot_chain"]
