//! Shared by the SP1 guest and host: the canonical statement/witness codec,
//! the exact hash framing of `veritor.protocol.merkle`, the pinned toy-ISA
//! semantics of `veritor.core.gates`, and the generic checker that decides one
//! batch of proof obligations.
//!
//! Everything here mirrors a Python module byte for byte; the cross-language
//! vectors in `tests/vectors.json` are generated by the Python side
//! (`tests/veritor/protocol/proofs/test_vectors.py`) and asserted here.

#![forbid(unsafe_code)]

pub mod check;
pub mod codec;
pub mod frame;
pub mod gateset;

pub use check::{check_batch, check_openings, check_relations, gate_set, CheckError};
pub use codec::{
    parse_statement, parse_witness, Arg, CodecError, CommitmentRef, GateOp, KindProgram,
    Obligation, Opening, PositionRef, Statement, Witness, STATEMENT_MAGIC, WITNESS_MAGIC,
};
pub use frame::{
    domain_id, empty_root, fold_path, framed_hash, leaf, merkle_depth, node, sha256,
    tagged_sha256, uint, uint_len, FRAME,
};
pub use gateset::{GateSet, Op};

/// The public values the guest commits: `sha256(statement bytes) || verdict`.
pub const PUBLIC_VALUES_LEN: usize = 33;

/// Lay out the public values for a statement digest and a verdict byte.
pub fn public_values(statement_digest: &[u8; 32], verdict: bool) -> [u8; PUBLIC_VALUES_LEN] {
    let mut out = [0u8; PUBLIC_VALUES_LEN];
    out[..32].copy_from_slice(statement_digest);
    out[32] = verdict as u8;
    out
}
