//! Cross-language vectors generated by the Python reference
//! (`tests/veritor/protocol/proofs/test_vectors.py`): the hash framing, the
//! gate-set digests and semantics, the codec and the checker's verdict on a
//! real batch must all agree byte for byte.

use serde::Deserialize;
use veritor_zk_common::{
    check_batch, check_openings, domain_id, empty_root, framed_hash, gate_set, leaf, node,
    parse_statement, parse_witness, sha256, tagged_sha256, uint, uint_len, CheckError, GateSet,
};

#[derive(Deserialize)]
struct Vectors {
    framing: Vec<Framing>,
    uint: Vec<Uint>,
    tagged_sha256: Vec<Tagged>,
    domains: Vec<Domain>,
    gate_sets: Vec<GateSetVector>,
    batch: Batch,
}

#[derive(Deserialize)]
struct Framing {
    tag: String,
    parts: Vec<String>,
    digest: String,
}

#[derive(Deserialize)]
struct Uint {
    value: u64,
    bytes: String,
}

#[derive(Deserialize)]
struct Tagged {
    tag: String,
    payload: String,
    digest: String,
}

#[derive(Deserialize)]
struct Leaf {
    rank: u64,
    position: u64,
    schema: String,
    value: String,
    digest: String,
}

#[derive(Deserialize)]
struct Node {
    level: u64,
    index: u64,
    left: String,
    right: String,
    digest: String,
}

#[derive(Deserialize)]
struct Domain {
    owner: i64,
    binding: String,
    identity: String,
    count: u64,
    domain_id: String,
    leaf: Leaf,
    node: Node,
    empty_root: String,
    root: String,
}

#[derive(Deserialize)]
struct Evaluation {
    op: String,
    a: u64,
    b: u64,
    out: u64,
}

#[derive(Deserialize)]
struct GateSetVector {
    id: String,
    width: u32,
    manifest: String,
    digest: String,
    evaluations: Vec<Evaluation>,
}

#[derive(Deserialize)]
struct Rejected {
    name: String,
    witness: String,
}

#[derive(Deserialize)]
struct Batch {
    statement: String,
    witness: String,
    statement_digest: String,
    obligations: usize,
    kinds: usize,
    gate_set_id: String,
    width: u32,
    verdict: bool,
    rejected_witnesses: Vec<Rejected>,
}

fn load() -> Vectors {
    let data = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors.json"))
        .expect("vectors.json (regenerate with VERITOR_WRITE_VECTORS=1 pytest tests/veritor/protocol/proofs)");
    serde_json::from_str(&data).expect("vectors.json parses")
}

fn unhex(text: &str) -> Vec<u8> {
    assert!(text.len() % 2 == 0, "odd hex length");
    (0..text.len())
        .step_by(2)
        .map(|at| u8::from_str_radix(&text[at..at + 2], 16).expect("hex"))
        .collect()
}

fn digest32(text: &str) -> [u8; 32] {
    unhex(text).try_into().expect("32-byte digest")
}

#[test]
fn framing_matches_merkle_py() {
    for case in load().framing {
        let parts: Vec<Vec<u8>> = case.parts.iter().map(|part| unhex(part)).collect();
        let refs: Vec<&[u8]> = parts.iter().map(Vec::as_slice).collect();
        assert_eq!(framed_hash(&unhex(&case.tag), &refs), digest32(&case.digest), "tag {}", case.tag);
    }
}

#[test]
fn uint_matches_merkle_py() {
    for case in load().uint {
        let bytes = uint(case.value);
        assert_eq!(&bytes[8 - uint_len(case.value)..], unhex(&case.bytes).as_slice(), "uint({})", case.value);
    }
}

#[test]
fn tagged_sha256_matches_identity_py() {
    for case in load().tagged_sha256 {
        assert_eq!(
            tagged_sha256(case.tag.as_bytes(), &unhex(&case.payload)),
            digest32(&case.digest),
            "tag {}",
            case.tag
        );
    }
}

#[test]
fn domains_leaves_and_nodes_match_commitment_domain() {
    for case in load().domains {
        let binding = digest32(&case.binding);
        let identity = digest32(&case.identity);
        let id = domain_id(&binding, (case.owner + 2) as u64, &identity, case.count);
        assert_eq!(id, digest32(&case.domain_id), "domain of owner {}", case.owner);
        assert_eq!(
            leaf(&id, case.leaf.rank, case.leaf.position, case.leaf.schema.as_bytes(), &unhex(&case.leaf.value)),
            digest32(&case.leaf.digest),
            "leaf of owner {}",
            case.owner
        );
        assert_eq!(
            node(&id, case.node.level, case.node.index, &digest32(&case.node.left), &digest32(&case.node.right)),
            digest32(&case.node.digest),
            "node of owner {}",
            case.owner
        );
        assert_eq!(empty_root(&id), digest32(&case.empty_root), "empty root of owner {}", case.owner);
        if case.count == 0 {
            assert_eq!(empty_root(&id), digest32(&case.root), "an empty domain's root is its empty root");
        }
    }
}

#[test]
fn gate_sets_match_core_gates_py() {
    for case in load().gate_sets {
        let set = GateSet::resolve(&case.id, case.width).unwrap_or_else(|| panic!("unknown gate set {}", case.id));
        assert_eq!(set.manifest(), case.manifest, "manifest of {}", case.id);
        assert_eq!(set.digest(), digest32(&case.digest), "digest of {}", case.id);
        for evaluation in case.evaluations {
            let op = set.op(&evaluation.op).unwrap_or_else(|| panic!("{} lacks {}", case.id, evaluation.op));
            assert_eq!(
                set.evaluate(op, evaluation.a, evaluation.b),
                evaluation.out,
                "{}({}, {}) at width {}",
                evaluation.op,
                evaluation.a,
                evaluation.b,
                case.width
            );
        }
    }
}

#[test]
fn a_real_batch_parses_and_checks() {
    let batch = load().batch;
    let statement_bytes = unhex(&batch.statement);
    assert_eq!(sha256(&statement_bytes), digest32(&batch.statement_digest));
    let statement = parse_statement(&statement_bytes).expect("statement parses");
    assert_eq!(statement.obligations.len(), batch.obligations);
    assert_eq!(statement.kinds.len(), batch.kinds);
    assert_eq!(statement.gate_set_id, batch.gate_set_id);
    assert_eq!(statement.width, batch.width);
    let witness = parse_witness(&unhex(&batch.witness)).expect("witness parses");
    let verdict = check_batch(&statement, &witness).is_ok();
    assert_eq!(verdict, batch.verdict);
    let set = gate_set(&statement).expect("known gate set");
    check_openings(&statement, &witness, &set).expect("openings authenticate");
}

#[test]
fn tampered_witnesses_are_rejected() {
    let batch = load().batch;
    let statement = parse_statement(&unhex(&batch.statement)).expect("statement parses");
    for rejected in batch.rejected_witnesses {
        let outcome: Result<(), CheckError> = match parse_witness(&unhex(&rejected.witness)) {
            Err(_) => Err(CheckError::WitnessShape("unparseable".into())),
            Ok(witness) => check_batch(&statement, &witness),
        };
        assert!(outcome.is_err(), "{} must be rejected", rejected.name);
    }
}

#[test]
fn statement_bytes_are_canonical_for_the_parser() {
    // A trailing byte, a truncated tail and a wrong magic are all rejected.
    let statement_bytes = unhex(&load().batch.statement);
    let mut trailing = statement_bytes.clone();
    trailing.push(0);
    assert!(parse_statement(&trailing).is_err());
    assert!(parse_statement(&statement_bytes[..statement_bytes.len() - 1]).is_err());
    let mut magic = statement_bytes.clone();
    magic[0] ^= 1;
    assert!(parse_statement(&magic).is_err());
}
