"""The recorder and the report: rows merge by ID, keep catalogue order, render section 4."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from veritor.stress import report
from veritor.stress.rows import Row, dump, load, record, row_key


def row(identifier: str, **overrides: object) -> Row:
    fields: dict[str, object] = {
        "id": identifier,
        "what": f"scenario {identifier}",
        "mechanism": "M1",
        "advice_bits": 0,
        "capacity_bits": 12,
        "overhead": 0.5,
        "description_bytes": 100,
        "verdict": "ok",
    }
    fields.update(overrides)
    return Row(**fields)  # type: ignore[arg-type]


def test_rows_sort_in_catalogue_order() -> None:
    identifiers = ["E1", "N2", "S10", "C6b", "S2", "C6a", "S1", "W1"]
    assert sorted(identifiers, key=row_key) == [
        "S1",
        "S2",
        "S10",
        "C6a",
        "C6b",
        "N2",
        "W1",
        "E1",
    ]
    with pytest.raises(ValueError):
        row_key("s1")
    with pytest.raises(ValueError):
        Row(
            id="bad id",
            what="",
            mechanism="",
            advice_bits=0,
            capacity_bits=0,
            overhead=0,
            description_bytes=0,
            verdict="",
        )


def test_row_validation() -> None:
    with pytest.raises(ValueError, match="advice_bits"):
        row("S1", advice_bits=-1)
    with pytest.raises(ValueError, match="capacity_bits"):
        row("S1", capacity_bits=1.5)
    with pytest.raises(ValueError, match="overhead"):
        row("S1", overhead=-0.1)
    assert row("S1", overhead=1 / 3).overhead == round(1 / 3, 6)


def test_record_merges_without_dropping_foreign_rows(tmp_path: Path) -> None:
    path = tmp_path / "stress.json"
    record(path, [row("S1"), row("N2", verdict="first")])
    merged = record(path, [row("N2", verdict="second"), row("C6a")])
    assert list(merged) == ["S1", "C6a", "N2"]
    assert merged["N2"].verdict == "second"
    text = path.read_text()
    assert text == dump(merged)
    assert json.loads(text)["S1"]["what"] == "scenario S1"
    assert load(path) == merged
    assert text.splitlines()[1].startswith(
        ' "S1": {"advice_bits": 0, "capacity_bits": 12, '
    )
    assert not [
        p for p in tmp_path.iterdir() if p.name.startswith(".stress")
    ]  # no temporaries left


def test_load_carries_other_recorders_fields_and_checks_the_file(
    tmp_path: Path,
) -> None:
    path = tmp_path / "stress.json"
    body = {
        **row("C2a").to_json(),
        "gates": 9285,
    }  # another recorder's row keeps its gate count
    path.write_text(json.dumps({"C2a": body}))
    loaded = load(path)
    assert loaded["C2a"].extra == {"gates": 9285} and loaded["C2a"].to_json() == body
    record(path, [row("S1")])
    assert (
        json.loads(path.read_text())["C2a"] == body
    )  # ... through a merge by another recorder too
    path.write_text(json.dumps({"S1": {**row("S1").to_json(), "what": 1}}))
    with pytest.raises(TypeError, match="what must be a string"):
        load(path)
    path.write_text("[]")
    with pytest.raises(TypeError, match="JSON object"):
        load(path)
    assert load(tmp_path / "missing.json") == {}


def test_report_replaces_only_the_results_section(tmp_path: Path) -> None:
    data = tmp_path / "data"
    data.mkdir()
    record(data / "stress.json", [row("S1", notes="a | note")])
    record(data / "stress-moe.json", [row("C2", what="MoE | routing", overhead=1234.5)])
    document = tmp_path / "stress-tests.md"
    document.write_text(
        "# Title\n\ntext\n\n## 3. Order\n\nkeep\n\n## 4. Results\n\nold table\n"
    )
    assert report.main(["--document", str(document), "--data", str(data)]) == 0
    text = document.read_text()
    head, _, body = text.partition("## 4. Results\n\n")
    assert head == "# Title\n\ntext\n\n## 3. Order\n\nkeep\n\n"
    assert "old table" not in body
    lines = body.splitlines()
    assert lines[0].startswith(
        "Generated by `python -m veritor.stress.report` from `docs/data/stress-moe.json`, "
    )
    assert lines[2] == "| " + " | ".join(report.COLUMNS) + " |"
    assert lines[4] == "| S1 | scenario S1 | M1 | 0 | 12 | 0.5 | 100 | ok |"
    assert lines[5] == "| C2 | MoE \\| routing | M1 | 0 | 12 | 1,234 | 100 | ok |"
    assert lines[-1] == "- **S1**: a \\| note"
    # a second run is a no-op, and --check agrees
    assert (
        report.main(["--document", str(document), "--data", str(data), "--check"]) == 0
    )
    assert document.read_text() == text
    record(data / "stress.json", [row("S2")])
    assert (
        report.main(["--document", str(document), "--data", str(data), "--check"]) == 1
    )
    assert document.read_text() == text
    with pytest.raises(ValueError, match="heading"):
        report.update("no heading here\n", "body\n")


def test_the_honest_prover_table_is_its_own_document(tmp_path: Path) -> None:
    data = tmp_path / "data"
    data.mkdir()
    record(data / "stress.json", [row("S1")])
    honest_row = Row(
        id="H3a",
        what="one flipped token, RU = request",
        mechanism="M6 post-J",
        advice_bits=0,
        capacity_bits=300,
        overhead=1.0,
        description_bytes=100,
        verdict="accepted",
        extra={"declarations": 1, "charge_bits": 76, "recompute": 0.125},
    )
    record(data / "stress-honest.json", [honest_row, row("H2a")])
    catalogue = tmp_path / "stress-tests.md"
    catalogue.write_text("# Catalogue\n\n## 4. Results\n\nold\n")
    document = tmp_path / "honest-prover.md"
    document.write_text("# Honest\n\ntext\n\n## Results\n\nold\n")
    argv = [
        "--document",
        str(catalogue),
        "--honest-document",
        str(document),
        "--data",
        str(data),
    ]
    assert report.main(argv) == 0
    # the catalogue never sees H rows, the honest document only them
    assert "H3a" not in catalogue.read_text()
    body = document.read_text().partition("## Results\n\n")[2]
    lines = body.splitlines()
    assert lines[0].startswith(
        "Generated by `python -m veritor.stress.report` from `docs/data/stress-honest.json`; "
    )
    assert lines[2] == "| " + " | ".join(report.HONEST_COLUMNS) + " |"
    assert lines[4] == "| H2a | scenario H2a | M1 | — | — | — | 12 | ok |"
    assert (
        lines[5]
        == "| H3a | one flipped token, RU = request | M6 post-J | 1 | 76 | 0.125 | 300 | accepted |"
    )
    assert report.main([*argv, "--check"]) == 0
    record(data / "stress-honest.json", [row("H2b")])
    assert report.main([*argv, "--check"]) == 1
    # a data directory without the honest file leaves the honest document alone
    (data / "stress-honest.json").unlink()
    document.write_text("untouched\n")
    assert report.main([*argv, "--check"]) == 0
    assert document.read_text() == "untouched\n"
