"""Stable architecture plug-in and registry surface."""

from .api import (
    NO_CONSTRUCTOR,
    ArchitectureId,
    ArchitecturePlugin,
    ArchitectureRegistry,
    CompileResult,
    ConfiguredPlugin,
    DecodingMode,
    GreedyTextExecutionShape,
)
from .builtin import (
    DEEPSEEK_V4_PRO_ARCHITECTURE_ID,
    DEEPSEEK_V4_PRO_NUMERICAL_PROFILE_ID,
    DEEPSEEK_V4_PRO_PLUGIN,
    DEMO_G_ARCHITECTURE_ID,
    DEMO_G_PLUGIN,
    GPT2_ARCHITECTURE_ID,
    GPT2_PLUGIN,
    INKLING_ARCHITECTURE_ID,
    INKLING_NUMERICAL_PROFILE_ID,
    INKLING_PLUGIN,
    KIMI_K3_ARCHITECTURE_ID,
    KIMI_K3_NUMERICAL_PROFILE_ID,
    KIMI_K3_PLUGIN,
    MATMUL_ARCHITECTURE_ID,
    MATMUL_PLUGIN,
    BatchInput,
    DeepSeekV4ProCompileRequest,
    DemoG,
    DemoGCompileRequest,
    DemoGPlugin,
    DotRequest,
    GPT2CompileRequest,
    InklingCompileRequest,
    KimiK3CompileRequest,
    MatmulCompileRequest,
    MatmulPlugin,
    compile_demo_g,
    compile_matmul,
    expected_dot_outputs,
    make_demo_request,
    matmul_expected_matrices,
)
from .registry import (
    ARCHITECTURE_PLUGINS,
    architecture_registry,
    compile_architecture,
    get_architecture_plugin,
    list_architecture_plugins,
    list_architectures,
)

type ArchitectureCompileRequest = (
    DemoGCompileRequest
    | MatmulCompileRequest
    | GPT2CompileRequest
    | KimiK3CompileRequest
    | DeepSeekV4ProCompileRequest
    | InklingCompileRequest
)

__all__ = [
    "ARCHITECTURE_PLUGINS",
    "DEEPSEEK_V4_PRO_ARCHITECTURE_ID",
    "DEEPSEEK_V4_PRO_NUMERICAL_PROFILE_ID",
    "DEEPSEEK_V4_PRO_PLUGIN",
    "DEMO_G_ARCHITECTURE_ID",
    "DEMO_G_PLUGIN",
    "GPT2_ARCHITECTURE_ID",
    "GPT2_PLUGIN",
    "INKLING_ARCHITECTURE_ID",
    "INKLING_NUMERICAL_PROFILE_ID",
    "INKLING_PLUGIN",
    "KIMI_K3_ARCHITECTURE_ID",
    "KIMI_K3_NUMERICAL_PROFILE_ID",
    "KIMI_K3_PLUGIN",
    "MATMUL_ARCHITECTURE_ID",
    "MATMUL_PLUGIN",
    "NO_CONSTRUCTOR",
    "ArchitectureCompileRequest",
    "ArchitectureId",
    "ArchitecturePlugin",
    "ArchitectureRegistry",
    "BatchInput",
    "CompileResult",
    "ConfiguredPlugin",
    "DecodingMode",
    "DeepSeekV4ProCompileRequest",
    "DemoG",
    "DemoGCompileRequest",
    "DemoGPlugin",
    "DotRequest",
    "GPT2CompileRequest",
    "GreedyTextExecutionShape",
    "InklingCompileRequest",
    "KimiK3CompileRequest",
    "MatmulCompileRequest",
    "MatmulPlugin",
    "architecture_registry",
    "compile_architecture",
    "compile_demo_g",
    "compile_matmul",
    "expected_dot_outputs",
    "get_architecture_plugin",
    "list_architecture_plugins",
    "list_architectures",
    "make_demo_request",
    "matmul_expected_matrices",
]
