"""Built-in architecture plug-ins."""

from ._call_dag_capacity import CallDagCapacityBoundProvider
from .deepseek_v4_pro import (
    DEEPSEEK_V4_PRO_ARCHITECTURE_ID,
    DEEPSEEK_V4_PRO_NUMERICAL_PROFILE_ID,
    DEEPSEEK_V4_PRO_PLUGIN,
    DeepSeekV4ProCompileRequest,
    DeepSeekV4ProPlugin,
    compile_deepseek_v4_pro,
    compile_deepseek_v4_pro_bound_model,
)
from .demo_g import (
    DEMO_G_ARCHITECTURE_ID,
    DEMO_G_PLUGIN,
    DemoGCapacityBoundProvider,
    DemoGCompileRequest,
    DemoGPlugin,
    compile_demo_g,
    demo_expected_outputs,
    demo_public_inputs,
)
from .gpt2 import (
    GPT2_ARCHITECTURE_ID,
    GPT2_PLUGIN,
    GPT2CapacityBoundProvider,
    GPT2CompileRequest,
    GPT2Plugin,
    compile_gpt2,
    compile_gpt2_structure,
)
from .inkling import (
    INKLING_ARCHITECTURE_ID,
    INKLING_NUMERICAL_PROFILE_ID,
    INKLING_PLUGIN,
    InklingCompileRequest,
    InklingPlugin,
    compile_inkling,
    compile_inkling_bound_model,
)
from .kimi_k3 import (
    KIMI_K3_ARCHITECTURE_ID,
    KIMI_K3_NUMERICAL_PROFILE_ID,
    KIMI_K3_PLUGIN,
    KimiK3CompileRequest,
    KimiK3Plugin,
    compile_kimi_k3,
    compile_kimi_k3_bound_model,
)
from .matmul import (
    MATMUL_ARCHITECTURE_ID,
    MATMUL_PLUGIN,
    MatmulCompileRequest,
    MatmulPlugin,
    compile_matmul,
    matmul_expected_matrices,
    matmul_expected_outputs,
    matmul_public_inputs,
)

__all__ = [
    "DEEPSEEK_V4_PRO_ARCHITECTURE_ID",
    "DEEPSEEK_V4_PRO_NUMERICAL_PROFILE_ID",
    "DEEPSEEK_V4_PRO_PLUGIN",
    "DEMO_G_ARCHITECTURE_ID",
    "DEMO_G_PLUGIN",
    "GPT2_ARCHITECTURE_ID",
    "GPT2_PLUGIN",
    "INKLING_ARCHITECTURE_ID",
    "INKLING_NUMERICAL_PROFILE_ID",
    "INKLING_PLUGIN",
    "KIMI_K3_ARCHITECTURE_ID",
    "KIMI_K3_NUMERICAL_PROFILE_ID",
    "KIMI_K3_PLUGIN",
    "MATMUL_ARCHITECTURE_ID",
    "MATMUL_PLUGIN",
    "CallDagCapacityBoundProvider",
    "DeepSeekV4ProCompileRequest",
    "DeepSeekV4ProPlugin",
    "DemoGCapacityBoundProvider",
    "DemoGCompileRequest",
    "DemoGPlugin",
    "GPT2CapacityBoundProvider",
    "GPT2CompileRequest",
    "GPT2Plugin",
    "InklingCompileRequest",
    "InklingPlugin",
    "KimiK3CompileRequest",
    "KimiK3Plugin",
    "MatmulCompileRequest",
    "MatmulPlugin",
    "compile_deepseek_v4_pro",
    "compile_deepseek_v4_pro_bound_model",
    "compile_demo_g",
    "compile_gpt2",
    "compile_gpt2_structure",
    "compile_inkling",
    "compile_inkling_bound_model",
    "compile_kimi_k3",
    "compile_kimi_k3_bound_model",
    "compile_matmul",
    "demo_expected_outputs",
    "demo_public_inputs",
    "matmul_expected_matrices",
    "matmul_expected_outputs",
    "matmul_public_inputs",
]
